### ISSUE TITLE
Add an in-game checkbox to the Title screen to enable/disable caching

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/gosch-game#18]
It would be great if we could register/unregister the service worker on the title screen. Maybe we can have a checkbox on the bottom-right corner to toggle this.

**Comment by ignacioxd** [comment]
Thanks! This is merged, but I am working on making the asset an actual checkbox, and allowing it to be visually toggled. For this, I'm creating a Checkbox.js UI class that can be reused in other parts of the game.

**Comment by adnanusman** [comment]
Sounds good, I'd love to see how that works. If I had found some documentation on how to implement a checkbox in phaser 3 I would have done it myself.

**Comment by ignacioxd** [comment]
Almost ready! I couldn't find any docs on this specifically, but I think I was able to put the pieces together. We'll see how it works shortly.
