### ISSUE TITLE
Assets issues

### ISSUE THREAD

**Issue by PepperAddict** [ignacioxd/gosch-game#27]
I need a list to help keep track of what I need to fix.

# Characters
- [x] mage 
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_orb_p
   * [x] character: centered, pivot point 0.5, 0.8 - named mage_hero
   * [x] fight, death, walk, stance, critical

- [x] knight
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_light
   * [x] character: centered, pivot point 0.5, 0.8 - named knight_hero
   * [x] fight, death, walk, stance, critical

- [x] priest
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_orb
   * [x] character: centered, pivot point 0.5, 0.8 - named priest_hero
   * [ ] fight, death, walk, stance, heal ( heal can be changed to critical)

- [x] fire monster
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_fire
   * [x] character: centered, pivot point 0.5, 0.8 - named fire_monster
   * [ ] fight, death, walk, stance, critical - (need to add critical to be even with the other players)

- [x] ice monster
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_ice
   * [x] character: centered, pivot point 0.5, 0.8 - named ice_monster
   * [ ] fight, death, walk, stance, critical - (need to add critical to be even with the other players)

- [x] spider monster
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_ven
   * [x] character: centered, pivot point 0.5, 0.8 - named spider_monster
   * [ ] fight, death, walk, stance, critical - (need to add critical to be even with the other players)

- [x] golem monster
   * [x] projectile: centered, pivot point 0.5, 0.5  - named proj_rock
   * [x] character: centered, pivot point 0.5, 0.8 - named golem_monster
   * [ ] fight, death, walk, stance, critical - (need to add critical to be even with the other players)

## If time permits

- [x] goblin monster (don't know what type he'll be... maybe an archer?)
   * [x] projectile: centered, pivot point 0.5, 0.5 - named proj_arrow  
   * [ ] character: centered, pivot point 0.5, 0.8 
   * [ ] fight, death, walk, stance, critical 

- [x] soldier (don't know what type he'll be... I can turn him into a thief)
   * [ ] projectile: centered, pivot point 0.5, 0.5  
   * [ ] character: centered, pivot point 0.5, 0.8 
   * [ ] fight, death, walk, stance, critical 

# Aura
- [x] healed  - has 8 frames
- [x] spawn/vanish - has 8 frames

Comment here if there's something I missed!

**Comment by ignacioxd** [comment]
Thanks for keeping this organized.

We need to make sure that every character is of the same size. Pivot points/anchors may be different per character if necessary.

With the new game mechanics, I think we need every character to shoot something. The spider may shoot out venom, and the priest may shoot out orbs of energy. I'm not sure what the knight might shoot out. Maybe lightning can come out of its sword?

I had not thought about bosses, but it can be something we can add to multiplayer mode, where people would have to collaborate to kill it instead of going after each other.

**Comment by PepperAddict** [comment]
Okay. I took out the bosses and added a different monster that I've made before to put in. 
added fire, ice, venom, lightning and orb projectile.

Let me know if there are anymore that needs to be added and fixed. 
The free trial for that texture thingymabobber is ending very soon! Aaaah! 😨

**Comment by ignacioxd** [comment]
Oooh, how about spawn/vanish animations? We can use these for connect/disconnect events.

I liked the boss idea! They could spawn at random intervals while everyone is battling each other and encourage them to fight together, if only for a little while. Players who contribute to kill a boss may get healed in proportion to how much damage they inflicted on the boss. But we can revisit this idea later.

**Comment by PepperAddict** [comment]
okay! will the spawn/vanish animation be an overlay like what I have planned for heal animation?.   maybe something like in star trek's transporter?

I may not have enough time for boss but I'll try and squeeze it in there after projectiles and the extra animation.

**Comment by ignacioxd** [comment]
Oh, no problem! Whatever is easier for you. You've already done waaaaaay more than I ever imagined.

**Comment by ignacioxd** [comment]
Looks like there's a problem with pivot points on the projectiles. They should be at the center of the projectile, I think. Check out the game-dev branch and click to shoot to see what I mean.

**Comment by PepperAddict** [comment]
is there a button to see projectiles? I can't see it.  But switching the pivot point to the center of the projectile will be no problem. the projectiles are already in the center so I'll just put it 0.5, 0.5

**Comment by PepperAddict** [comment]
I put the pivot point to the projectile's center for each one, but I noticed it's still off. I think it's because the projectiles are actually NOT in the center of the frame.  Hopefully that fixes it.

**Comment by ignacioxd** [comment]
If you click on the map, projectiles should appear. There will be a bounding box and a green line. The green line indicates the vector of motion and the center of the tile. For some reason the tile looks huge and the projectile is not centered on it.

**Comment by ignacioxd** [comment]
The scale is modified in code, don't worry about it.

**Comment by PepperAddict** [comment]
Okay, I think I got it. But I just want to confirm with you before I move on to the other projectiles.
![proj](https://user-images.githubusercontent.com/4171505/37352976-c6e823f4-26b4-11e8-84c3-ded1663b8311.png)

**Comment by ignacioxd** [comment]
Nice! They look centered now. I wonder why the tiles are so large.

**Comment by levyadams** [comment]
when I was messing with the scaling it pushes the sprite to 0,0 as well as the box, so instead of centering them or whatever you can just scale the box down the size of the sprite and it all lined up for me.
