### ISSUE TITLE
We need a name for our game

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/gosch-game#34]
Title says it all. Any thoughts?

**Comment by levyadams** [comment]
ragin mages

**Comment by PepperAddict** [comment]
I love it @levyadams ! it's catchy and it kind of rhymes

**Comment by adnanusman** [comment]
Rogue warriors
Magic vs Metal
Supreme Arena
Of warriors and mages

**Comment by ignacioxd** [comment]
Some additional names suggested during our meeting on 3/16 were:

- Asteroids v2
- Shooty McPoopy
- Pixel Explosion
- Immortal Battlegrounds
- Projectile Vomit

Don't shoot the messenger :)

**Comment by ignacioxd** [comment]
Looks like we're going with **Ragin' Mages**!
