### ISSUE TITLE
Title screen navigation

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/gosch-game#36]
We need to add two buttons to the main screen: one to start the game in single player mode, and the second to start it in multiplayer mode. These buttons will open the character selection screen (see #35), but they need to pass in the game mode that the user requested as data.

**Comment by levyadams** [comment]
I'll work on this.

**Comment by ignacioxd** [comment]
@levyadams according to the last meeting minutes, PepperAddict and Laura are working on the title screen. You may want to touch base with them before you start working on this so that the three of you can collaborate.

**Comment by PepperAddict** [comment]
Okay, just in case someone missed Friday's meeting. I'll work on this with @levyadams 's guidance.

**Comment by ignacioxd** [comment]
@PepperAddict since you are working on the title page, maybe you can also add functionality to address #67. The checkbox to make the game available offline should only be shown on systems that support service workers. There's a method to check this already in the `ServiceWorker` class.

**Comment by PepperAddict** [comment]
@ignacioxd I don't know where to start with that I haven't even started to try and figure out a way to show disabled for multiplayer if there's no internet (if there's an option for that).  This might be a bit advanced for me.

**Comment by ignacioxd** [comment]
@PepperAddict no problem. The disabled for multiplayer can be added later, once we factor out the Socket.io stuff from the GameScene.

I just added 11d8fcb68bdec5e6d8a530c3fe543753d1aa54b8 to fix #67. It does something like this:

```javascript
if(ServiceWorker.isSupported()) {
  //Put checkbox here
}
```

**Comment by ignacioxd** [comment]
This was closed by #64
