### ISSUE TITLE
Server-side websocket protocol implementation

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/gosch-game#38]
This is dependent on #37

**Comment by D1esel-Dev** [comment]
I looked over what you had and here are some index.js suggestions:
Also wondering if we are serving the index html and required static assets via the server too, correct?

Using node http server:
```javascript
// import dependencies
const server = require('http').createServer(handler)
const io = require('socket.io')(server);
// make port the env port or port of choosing
const PORT = process.env.PORT || 3030;

// serve index.html


// serve static files


// run server
server.listen(PORT, () => {
    console.log(`Server is listening on ${PORT}`);
});

// socket.io emit and recieve events

```
Using Express:
```javascript
// import dependencies
const app = require('express')();
const server = require('http').Server(app);
const io = require('socket.io')(server);
// make port the env port or port of choosing
const PORT = process.env.PORT || 3030;


// serve index.html


// serve static files


// run server
server.listen(PORT, () => {
    console.log(`Server is listening on ${PORT}`);
});

// socket.io emit and recieve events

```

Thoughts?

**Comment by ignacioxd** [comment]
The current approach is to have the game server be completely independent from the game, so two separate servers. The idea is to be able to host the two separately, if needed. For example, we may have a test server running on a remote machine, and we would connect to that game server from a local instance of the game (in development).

Being able to specify the listening port is a good idea though. Feel free to open a pull request for that.

**Comment by D1esel-Dev** [comment]
Ah yeah good idea to have the game and then the multiplayer server its own entities, one to serve the game and one for the multiplayer server. I hope your not meaning they have to be on different environments? So say express in one file for the game itself, and then socket.io in a different server file for multiplayer server only? We could also make it easier then to create 2 different environment port variables, game server port and multiplayer server port.

**Comment by ignacioxd** [comment]
Express and socket.io are both on the same server, but if I understand you correctly they will indeed be on different environments. They can be in different machines.

I had missed a statement binding socketio to the server, but this is now fixed.

Another advantage of decoupled game servers is that we could have multiple! Then some people could join "arena1" while others could join "arena2" by selecting a different server.

**Comment by ignacioxd** [comment]
I'm closing this since we have a working server-side websocket implementation. We can open more specific issues as needed.
