### ISSUE TITLE
Socket.io library client-side integration

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/gosch-game#40]
This will be very similar to what is currently being done for the Phaser engine in Gulp.

- Add Socket.io as dependency
- Create and integrate Gulp task to deploy the Socket.io client library into the game build folder
- Load the Socket.io client library from the HTML

**Comment by rhon3n** [comment]
I'd like to work on this.

**Comment by ignacioxd** [comment]
@rhon3n alright! Looking forward to your PR.
