### ISSUE TITLE
Animations/physics motion + input freezes completely after 10 seconds

### ISSUE THREAD

**Issue by levyadams** [ignacioxd/gosch-game#49]
Anyone else getting this? All of my animations stop and the character no longer moves, and no shooting. Game-dev branch

**Comment by ignacioxd** [comment]
I'm unable to reproduce this on my end. Do you just let the game run for 10 seconds, or do you interact with it at all?

Can anyone confirm if it works/breaks for them?

**Comment by levyadams** [comment]
No I move around and fire. The animations go first, then the controls. I am on canary..I get no errors or anything.

**Comment by ignacioxd** [comment]
Do you mind trying on a different browser, or on stable Chrome?

**Comment by levyadams** [comment]
Firefox : Works fastest.
Chrome: Works.
Canary : NOT SUPPORTED! Runs but things are broken badly.
IE: Couldn't get it to run...someone else try as well.

**Comment by levyadams** [comment]
I considering this issue closed since its just the exp browser. Now we know!
