### ISSUE TITLE
Alternative projectile range

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/gosch-game#65]
I was working with `tween`s today as an alternative to the timer approach.  Here is a sample of a tween projectile that fades with time.  Using tweens we can add different effects, such as a fireball that gets bigger as it goes. or a scatter gun. 
[ProjectileExample.zip](https://github.com/ignacioxd/gosch-game/files/1844006/ProjectileExample.zip)

The code is simple:
```js
 let tween= scene.add.tween({
      targets: this,
      alpha: 0,
      ease: 'Linear',
      delay: 400,
      duration: 750,
      onComplete: this._rangeReached,
      onCompleteParams: [ this ]
    });
```
and 
```js
 _rangeReached(tween, targets, projectile) {
    console.log('Kill message received');
    // this.timedEvent.remove(false);
    projectile.destroy();
  }
```
You can see an example on my fork the game-dev-projectile-upgrade branch.
https://github.com/AtlantaDancer/gosch-game/blob/game-dev-projectile-upgrade/game/src/js/objects/Projectile.js

**Comment by ignacioxd** [comment]
Nice! I like this approach better than the regular time-based. This has a lot more potential. Feel free to PR with this to replace the time-based one.

Is `delay` there doing anything? I see a `loopDelay` property in the docs, but not a `delay` property.

Do you know if we need to clean up the tweens that are added to the scene? Maybe they are removed automatically, but we should find out.

**Comment by AtlantaDancer** [comment]
There are 2 things that happen with this.  An effect that is gradual and the end effect. 

1. Change the transparency (alpha)
    - go from current alpha (1= opaque) to alpha of 0 (full transparency) 
    - do the transition in a linear fashion (ease: Linear)
    - Wait to start change for .4 seconds (delay setting)
    - continue after delay for .75 seconds (duration)
2. At the end of the full time (delay + transition) call the call back function
    - the callback then removes the projectile

The gradual effect is how we can achieve things like frost rays that get wider as they progress or fireballs that expand as they move away from the character, etc.

I will look at the tweens and need to remove.  We may simply have a tween object for the scene which is passed into the projectile and add tween events to the single tween.  I will get back to you or have it in the PR when I do it.
