### ISSUE TITLE
Leaner character creation

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/gosch-game#66]
We currently have a separate class/file for each possible character.  We could consolidate.  Have a single character class that has a constructor that individualizes the character.  The config information can be stored in a config json file - probably assets.json.  When we want to create the character we can either pass in configuration or key identifier and then set properties.  Current character properties are:

- Key
- Animation
- colSize
- offSetX
- offSetY
- Projectile type
- Projectile Range
- Speed

With the list of characters in a json file we can pass the character list into `buildAnimations` instead of having the defined list in the routine.
If a new json file is used `BootScene` has an example of loading the json into the cache and is where the new json can be loaded.  `LoaderScene` has an example of pulling information from the cached json file and then using the information.

Adding a new character won't require code - simply adding assets and adding character information to the json file.

**Comment by ignacioxd** [comment]
Sure, this will potentially make the character loading screen a bit more dynamic as well. Especially if we use a carousel style selector.

What's the JSON structure you propose?

**Comment by AtlantaDancer** [comment]
Here is one possible format with stacked options ( collider: {Size: 70, Offset: {x: 0, y: 0}}) instead of the flattened (colliderSize: 70, colliderOffsetX:0, colliderOffsetY:0).  Either one will work...  As you can see I added the title and descriptions which can be used in the character selection screen.
 
> {
        title: "Valiant Knight",
        key: "knight_hero",
        Description: "This is the text for the character selection screen",
       scale: 0.35,
        Orientation: "E",
        speed: 200,
        projectile: {
             Type: 'fire',
             Range: 1000,
             Offset: {x: 0, y: -150}
             },
        collider: {
             Size: 70,
             Offset: {x: 0, y: 0}
             }
}

**Comment by ignacioxd** [comment]
I like the nested structure. More like

```javascript
{
  name: "Valiant Knight",
  key: "knight_hero",
  description: "This is the text for the character selection screen",
  scale: 0.35,
  orientation: "E",
  baseSpeed: 200,
  projectile: {
    type: 'fire',
    baseRange: 1000,
    offset: {x: 0, y: -150}
  },
  collider: {
    size: 70,
    offset: {x: 0, y: 0}
  }
}
```
This should be placed in a separate file, maybe `characters.json`, and not in the `assets.json`. The `assets.json` will then have a reference to this file. I think we need a new asset category in `assets.json` and a new `assets/json` folder. In addition to `image`, `tileMap`, etc. maybe we can have `json` also.

Would you like to work on this? Maybe a first pass is to add this new JSON file and use it in the character selection screen (updating #72). Then, character creation could be its own PR. How does this sound?

**Comment by AtlantaDancer** [comment]
Sounds good.  I've updated the PR for character selection #72 .  I did a base version of the characters.json.  I can start working on character creation including an expanded json file.
