### ISSUE TITLE
Create first map

### ISSUE THREAD

**Issue by ignacioxd** [ignacioxd/gosch-game#9]
A basic map is currently loaded in the game. We need to create a more interesting first map that can be used to test the game mechanics. The use of [Tiled](http://www.mapeditor.org/) is recommended to generate the JSON file required to load the map. The current map can be used as a starting template.

**Comment by adnanusman** [comment]
I've created a basic map, created a new scene and added a PR.

**Comment by ignacioxd** [comment]
Thanks, @adnanusman (see #15)
